version: '3'
services:
  phsa-unixlinux-web-dashboard:
    image: phsa-unixandlinux-dash-rockylinux9:v1.0
    #    hostname: rocky8-systemd-server
    restart: always
#commented by sucar 4/24/2023
#checked lots of documentation systemd doesnt work without privileged command
    privileged: true
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/Vancouver
    ports:
      - "3000:3000"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data/src:/root/dashboardDevelopment/src:rw
      - ./data/public:/root/dashboardDevelopment/public:rw
